firstproject/discussion_board/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('boards.url')),
    path('',include('accounts.url')),
]

firstproject/accounts/models.py
from django.db import models

# Create your models here.

firstproject/boards/models.py
from django.db import models
from  django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    name=models.CharField(max_length=50,unique=True)
    description=models.CharField(max_length=150)
    def __str__(self):
        return self.name
class Topic(models.Model):
    subject = models.CharField(max_length=255)
    board=models.ForeignKey(Board,related_name="topics",on_delete=models.CASCADE)
    created_by=models.ForeignKey(User,related_name="topics",on_delete=models.CASCADE)
    created_dt=models.DateTimeField(auto_now_add=True)
class Post(models.Model):
    message=models.TextField(max_length=4000)
    topic=models.ForeignKey(Topic,related_name="posts",on_delete=models.CASCADE) #posts=comments
    created_by = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)

firstproject/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class SignUpForm(UserCreationForm):
    email=forms.CharField(
        max_length=255,
        required=True,
        widget=forms.EmailInput()
    )
    class Meta:
        model=User
        fields={'username','email','password1','password2'}

firstproject/boards/forms.py
from django import forms
from .models import Topic,Post
class NewTopicForm(forms.ModelForm):
    message=forms.CharField(widget=forms.Textarea(
        attrs={'rows':5,'placeholder':"write your message here"}
    ),max_length=4000,
    help_text="the maw length od the text is 4000"
                            )
    class Meta:
        model=Topic
        fields=['subject','message']
class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['message',]

firstproject/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login,logout
from .forms import SignUpForm
# Create your views here.

def signup(request):
    form = SignUpForm()
    if request.method =='POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('home')

    return render(request,'signup.html',{'form':form})
def logoutUser(request):
    logout(request)
    return  redirect('home')

firstproject/boards/views.py
import http.client

from django.shortcuts import render, get_list_or_404, redirect, get_object_or_404
from django.http import HttpResponse,Http404
from .models import Board,Topic,Post
from  django.contrib.auth.models import User
from  .forms import NewTopicForm,PostForm
from django.contrib.auth.decorators import login_required
def home(request):
    boards=Board.objects.all()
    return render(request,'home.html',{'boards':boards})
def board_topics(request,board_id):
    try:
      board=Board.objects.get(pk=board_id)
    except:
        raise Http404
    print("-----------------------")
    print(board)
    return render(request, 'topics.html', {'board': board})
 #topic=get_list_or_404(Board,pk=board_id)


''' board_names=[]
    for element in board:
        board_names.append(element.name)
    response_html='<br>'.join(board_names)
    return HttpResponse(response_html)'''
@login_required

def new_topic(request,board_id):
    try:
        board = Board.objects.get(pk=board_id)
    except:
        raise Http404
    '''  forms html simple
    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']
        user=User.objects.first()
        topic=Topic.objects.create(
            subject=subject,
            board=board,
            created_by=user
        )
        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=user
        )
        return  redirect('board_topics',board_id=board.pk)
        print(subject,message)'''
    #forms of django
    #user = User.objects.first()
    if request.method == 'POST':
        form=NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.created_by = request.user
            topic = form.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
            return redirect('board_topics', board_id=board.pk)
    else:
        form = NewTopicForm()

    return render(request,'new_topic.html',{'board': board,'form':form})

def topic_posts(request,board_id,topic_id):
    topic = get_object_or_404(Topic,board__pk=board_id,pk=topic_id)
    return render(request,'topic_posts.html',{'topic':topic})
@login_required
def reply_topic(request, board_id,topic_id):
    topic = get_object_or_404(Topic,board__pk=board_id,pk=topic_id)
    if request.method == "POST":
        form =PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()

            return redirect('topic_posts',board_id=board_id, topic_id = topic_id)
    else:
        form = PostForm()
    return render(request,'reply_topic.html',{'topic':topic,'form':form})





# Create your views here.

firstproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">

</head>
<body>
{%block body%}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainMenu">
      {%if user.is_authenticated%}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="#">My account</a>
            <a class="dropdown-item" href="#">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        </li>
      </ul>
        {%else%}
        <form class="form-inline ml-auto">
        <a href="{%url 'login'%}" class="btn btn-outline-secondary">login</a>
        <a href="{%url 'signup'%}" class="btn btn-primary ml-2">Signup</a>
        </form>
            {%endif%}

    </div>
  </div>
</nav>
<div class="container">
     <ol class="breadcrumb my-4">
       {%block breadcrumb%}
       {%endblock%}
    </ol>

    {%block content%}
    {%endblock%}

</div>
{%endblock body%}
<script src="{% static 'js/jquery-3.7.1.min.js'%}"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
</body>
</html>

firstproject/templates/change_password.html
{% extends 'base.html' %}
{%block title%}Change password{%endblock%}
{%block breadcrumb%}
<li class="breadcrumb-item active"><small class="text-muted">change password</small></li>
{%endblock%}
{%block content%}
<form method="post" novalidate >
   {% csrf_token %}
    {%include 'include/forms.html'%}


    <button type="submit" class="btn btn-success d-block">change</button>


</form>
{%endblock%}

firstproject/templates/change_password_done.html
{% extends 'base.html' %}
{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item "><a href="{%url 'change_password'%}">Change Password</a> </li>

  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}

<div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

firstproject/templates/home.html
{% extends 'base.html' %}
{%block title%}Boards{%endblock%}
{%block breadcrumb%}<li class="breadcrumb-item active">boards</li>{%endblock%}
{%block content%}
 <table class="table">
    <thead class="table-dark">
    <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topic</th>
        <th>Last posts</th>
    </tr>
    </thead>
    <tbody>
    {% for element in boards%}
    <tr>
        <td>
           <a href="{%url 'board_topics' element.pk%}">{{element.name}}</a>
            <small class="text-muted d-block">{{element.description}}</small>

        </td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
    </tr>
    {%endfor%}
    </tbody>
</table>
{%endblock%}

firstproject/templates/include/forms.html
{%load widget_tweaks%}

{%for field in form%}
    <div class="form-group">
        {{field.label_tag}}
         {%if form.is_bound%}
            {%if field.errors%}
               {%render_field field class="form-control is-invalid"%}
               {%for error in field.errors%}
                   <div class="invalid-feedback">{{error}}</div>
               {%endfor%}
            {%else%}
               {%render_field field class="form-control is-valid"%}
            {%endif%}

         {%else%}
            {%render_field field class="form-control"%}
         {%endif%}


    </div>
    {%if field.help_text%}
    <small class="form-text text-muted">{{field.help_text}}</small>
    {%endif%}
    {%endfor%}

firstproject/templates/login.html
{% extends 'base.html' %}

   {%block body%}
<div class="container">
    <h1>Login</h1>
    <form method="post" novalidate >
        {%csrf_token%}
        {%include 'include/forms.html'%}
        <button type="submit" class="btn btn-primary d-block">Submit</button>
         <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'signup'%}">Sign Up</a>
          </div>

    </form>

</div>

   {%endblock%}

firstproject/templates/new_topic.html
{% extends 'base.html' %}
{%block title%}create new topic{%endblock%}
{%block breadcrumb%}<li class="breadcrumb-item "><a href="{%url 'home'%}">Boards</a></li>
        <li class="breadcrumb-item "><small class="text-muted"><a href="{%url 'board_topics' board.pk%}">{{board.name}}</a></small></li>
<li class="breadcrumb-item active"><small class="text-muted">New topic</small></li>
{%endblock%}
{%block content%}
<form method="post" novalidate >
   {% csrf_token %}
    {%include 'include/forms.html'%}


    <button type="submit" class="btn btn-success d-block">Add</button>
    <!--<div class="form-group">
         <label for="id_subject">Subject</label>
        <input type="text" class="form-control" name="subject" id="id_subject" >

    </div>
    <div><label class="d-block">Message</label>
    <textarea name="message" class="form-control" id="id_message" rows="5"></textarea>

    </div>-->


</form>
{%endblock%}

firstproject/templates/reply_topic.html
{% extends 'base.html' %}
{%load static%}
{%block title%}{{topic.subject}} {%endblock%}
{% block breadcrumb %}

   <li class="breadcrumb-item "><a href="{% url 'home' %}">Boards</a></li>
   <li class="breadcrumb-item "><a href="{% url 'board_topics' topic.board.pk  %}">{{ topic.board.name}}</a></li>

        <li class="breadcrumb-item active">{{topic.subject}}</li>
        <li class="breadcrumb-item active">Post Reply</li>
{%endblock%}
{%block content%}
<form method="post" class="mb-4" >
   {% csrf_token %}
    {%include 'include/forms.html'%}
    <br>
<button type="submit" class="btn btn-success d-block">Post Reply</button>
</form>

{%for post in topic.posts.all %}
   <div class="col-10">
        <div class="row mb-3">
            <div class="col-6">
                <strong class="text-muted">{{post.created_by.username}}</strong>
            </div>
            <div class="col-6">
                <small class="text-muted">{{post.created_dt}}</small>
            </div>

        </div>
        {{post.message}}
    </div>
{%endfor%}
{%endblock%}

firstproject/templates/signup.html
{% extends 'base.html' %}

   {%block body%}
<div class="container">
    <h1>SignUp</h1>
    <form method="post" novalidate >
        {%csrf_token%}
        {%include 'include/forms.html'%}
        <button type="submit" class="btn btn-primary d-block">Create New User</button>
         <div class="card-footer text-muted text-center">
           create new account <a href="{%url 'login'%}">Log in</a>
          </div>

    </form>

</div>

   {%endblock%}

firstproject/templates/topic_posts.html
{% extends 'base.html' %}
{%load static%}
{%block title%}{{topic.subject}} {%endblock%}
{% block breadcrumb %}

   <li class="breadcrumb-item "><a href="{% url 'home' %}">Boards</a></li>
   <li class="breadcrumb-item "><a href="{% url 'board_topics' topic.board.pk  %}">{{ topic.board.name}}</a></li>

        <li class="breadcrumb-item active">{{topic.subject}}</li>
{%endblock%}
{%block content%}
<a href="{% url 'reply_topic' topic.board.pk topic.pk  %}" class="btn btn-primary btn-sm" role="button">Reply</a>
{%for post in topic.posts.all%}
<div class="card mb-2">
<div class="card-body p-3">
        <div class="row">
    <div class="col-2">
        <img src="{%static 'img/r.png'%}" alt="{{post.created_by.username}}" class="w-75">
    </div>
    <div class="col-10">
        <div class="row mb-3">
            <div class="col-6">
                <strong class="text-muted">{{post.created_by.username}}</strong>
            </div>
            <div class="col-6">
                <small class="text-muted">{{post.created_dt}}</small>
            </div>

        </div>
        {{post.message}}
        {%if post.created_by == user%}
        <div class="mt-3">
                 <a href="#" class="btn btn-primary btn-sm" role="button">Edit</a>
        </div>
        {%endif%}
    </div>
</div>
</div>
</div>

{%endfor%}

{%endblock%}

firstproject/templates/topics.html
{% extends 'base.html' %}
{%block title%}topics{%endblock%}
{%block breadcrumb%}<li class="breadcrumb-item "><a href="{%url 'home'%}">Boards</a></li>
        <li class="breadcrumb-item active"><small class="text-muted">{{board.name}}</small></li>
{%endblock%}
{%block content%}
<div>
    <a href="{%url 'new_topic' board.pk%}" class="btn btn-success">New Topic</a>
</div>
<br>
 <table class="table">
    <thead class="table-dark">
    <tr>
        <th>Topic</th>
        <th>Created by</th>
        <th>Posts</th>
        <th>views</th>
        <th>Created dt</th>
    </tr>
    </thead>
    <tbody>
    {% for element in board.topics.all%}
    <tr>
        <td><a href="{%url 'topic_posts' board.pk element.pk %}">{{element.subject}}</a></td>
        <td>{{element.created_by.username}} </td>
        <td>0</td>
        <td>0</td>
        <td>{{element.created_dt}}</td>
    </tr>
    {%endfor%}
    </tbody>
</table>
{%endblock%}